config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount MaintenanceTasks::Engine => "/maintenance_tasks"
    require "sidekiq/web"
    Sidekiq::Web.app_url = "/"
    mount Sidekiq::Web => "/sidekiq"
  end

  namespace :waitlist do
    resources :users, only: %i[ new create ]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: 'pages#index', as: :app_index

  # ref https://stackoverflow.com/questions/17743696/rails-routing-resources-with-only-custom-actions
  scope '/', controller: :pages do
    get :index
    get :privacy_policy
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/waitlist.rb
module Waitlist
  def self.table_name_prefix
    "waitlist_"
  end
end

app/models/waitlist/user.rb
# == Schema Information
#
# Table name: waitlist_users
#
#  id                     :bigint           not null, primary key
#  business_type          :integer          not null
#  email_address          :string(319)      not null
#  notes                  :string(1024)
#  original_email_address :string(319)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
class Waitlist::User < ApplicationRecord
  enum business_type: {
    "Personal Use" => 0,
    "Start-up" => 1,
    "Agency/Consultancy" => 2,
    "Enterprise" => 3
  }

  validates :email_address, presence: true
  validates :business_type, presence: true
  validates :email_address, length: { in: 4..319 }, uniqueness: true, unless: ->(user) { user.email_address.blank? }
  validates :notes, length: { maximum: 1024 }
  validates :business_type, inclusion: business_types.keys, unless: ->(user) { user.business_type.blank? }

  encrypts :email_address, deterministic: true, ignore_case: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/current_waitlist_user.rb
module CurrentWaitlistUser
  private
    def set_waitlist_user
      @waitlist_user = Waitlist::User.find(session.fetch(:waitlist_user, nil))
    rescue ActiveRecord::RecordNotFound
      @waitlist_user = Waitlist::User.new
    end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

# PagesController handles routes/actions for
# static pages like the #index (home) page.
class PagesController < ApplicationController
  include CurrentWaitlistUser
  before_action :set_waitlist_user

  # Action for the index/home route.
  def index; end
  # Action for the privacy policy route.
  def privacy_policy; end
  # Action for the terms of service route.
  def terms_of_service; end
end

app/controllers/waitlist/users_controller.rb
class Waitlist::UsersController < ApplicationController

  # GET /waitlist/users/new
  def new
    @waitlist_user = Waitlist::User.new
  end

  # POST /waitlist/users or /waitlist/users.json
  def create
    @waitlist_user = Waitlist::User.new(waitlist_user_params)

    respond_to do |format|
      if @waitlist_user.save
        # Set waitlist_user in session
        session[:waitlist_user] = @waitlist_user.id

        format.html { redirect_to app_index_url, notice: I18n.t('waitlist.users.controllers.create.success') }
        format.json { render :show, status: :created, location: @waitlist_user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @waitlist_user.errors, status: :unprocessable_entity }
      end
    end
  end

  private

    # Only allow a list of trusted parameters through.
    def waitlist_user_params
      params.require(:waitlist_user).permit(:email_address, :business_type, :notes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/waitlist/users_helper.rb
module Waitlist::UsersHelper
end

app/views/layouts/_header.html.erb
<div class="header-container mt-12">
  <%= link_to app_index_url do %>
    <%= image_tag "kwux_logo.png", class: "mx-auto mb-4 md:mb-8" %>
  <% end %>

  <%= turbo_frame_tag 'navigation' do %>
    <%#= render "layouts/nav" %>
  <% end %>
</div>

app/views/layouts/_nav.html.erb
<div
  class="flex flex-col items-center justify-center space-y-3 md:flex-row md:space-y-0 md:space-x-8 md:justify-center">
  <div class="hidden group md:block">
    <a href="#">About</a>
    <div class="mx-1 mt-1 duration-500 border-b-2 opacity-0 border-blue-400 group-hover:opacity-100"></div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:page_title) ? yield(:page_title) : t('.title') %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <%= javascript_importmap_tags %>
    <%= hotwire_livereload_tags if Rails.env.development? %>
    <script src="https://kit.fontawesome.com/b1ed12b0ad.js" crossorigin="anonymous"></script>
    <%= render "shared/analytics_resources" %>
  </head>

  <body>
    <%= render "layouts/header" %>

    <main class="container max-w-6xl mx-auto mt:4 md:mt-8 px-5">
      <%= yield %>
    </main>

    <%= render "layouts/footer" %>
  </body>
</html>

app/views/pages/_waitlist_signup.html.erb
<%= turbo_frame_tag Waitlist::User.new, class: 'w-full md:w-1/2 flex flex-col justify-center items-center' do %>
  <% if waitlist_user and waitlist_user.persisted? %>
    <div class="flex flex-col justify-center items-center space-y-6 text-center">
      <h2 class="font-semibold text-2xl">
        <%= t('.success.header') %>
      </h2>
      <h3 class="w-3/4">
        <%= t('.success.subheader') %>
      </h3>
      <div class="w-3/4">
        <p>
          Send an email to <span class="whitespace-pre bg-blue-300 rounded-md shadow-solid-sm shadow-black px-1 md:px-3 py-1 font-semibold uppercase text-xs leading-tight">mo [at] kwux.com</span> if you want
          to be part of our pre-launch user group!
        </p>
      </div>
    </div>
  <% else %>
    <h2 class="font-semibold text-2xl mx-auto">Sign up for the Waitlist!</h2>
    <%= render partial: 'waitlist/users/form', locals: { waitlist_user: @waitlist_user } %>
  <% end %>
<% end %>

app/views/pages/privacy_policy.html.erb
<div class="container mx-auto mt-8">
  <div class="flex flex-col">

    <h1 class="mb-4"><%= t(".title") %></h1>


    <p class="mb-4 text-xl text-gray-700 leading-normal">
      Last revised on 2022-05-04
    </p>

    <h5>
      The Gist
    </h5>

    <p class="mb-4 text-sm text-gray-700 leading-normal">
      Kwux will collect certain non-personally identify information about you as you use our sites.
      We may use this data to better understand our users. We can also publish this data,
      but the data will be about a large group of users, not individuals.
    </p>

    <p class="mb-4 text-sm text-gray-700 leading-normal">
      We will also ask you to provide personal information, but you'll always be able to opt out. If you give us
      personal
      information, we won't do anything evil with it.
    </p>

    <p class="mb-4 text-sm text-gray-700 leading-normal">
      We can also use cookies, but you can choose not to store these.
    </p>

    <p class="mb-4 text-sm text-gray-700 leading-normal">
      That's the basic idea, but you must read through the entire Privacy Policy below and agree with all the details
      before
      you use any of our sites.
    </p>

    <h5>
      Reuse
    </h5>

    <p class="mb-4 text-sm text-gray-700 leading-normal">
      This document is based upon the
      <%= link_to "Automattic Privacy Policy", "http://automattic.com/privacy/" %> and is licensed under
      <%= link_to "Creative Commons Attribution Share-Alike License 2.5", "http://creativecommons.org/licenses/by-sa/2.5/" %>
      .
      Basically,
      this means you can use it verbatim or edited, but you must release new versions under the same license and you
      have
      to
      credit Automattic somewhere (like this!). Automattic is not connected with and does not sponsor or endorse Kwux or
      its
      use of the work.
    </p>

    <p class="mb-4 text-sm text-gray-700 leading-normal">
      Kwux, a product of uMKR, Inc., ("Kwux") makes available services include our web sites (kwux.com and
      www.kwux.com),
      our blog, our software products, our API, and
      any other
      software, sites, and services offered by Kwux in connection to any of those (taken together, the "Service"). It is
      Kwux's policy to respect your privacy regarding any information we may collect while operating our websites.
    </p>

    <h5>
      Questions
    </h5>

    <p class="mb-4 text-sm text-gray-700 leading-normal">
      If you have question about this Privacy Policy, please contact us at mo@kwux.com
    </p>

    <h5>
      Visitors
    </h5>

    <p class="mb-4 text-sm text-gray-700 leading-normal">
      Like most website operators, Kwux collects non-personally-identifying information of the sort that web browsers
      and
      servers typically make available, such as the browser type, language preference, referring site, and the date and
      time
      of each visitor request. Kwux's purpose in collecting non-personally identifying information is to better
      understand
      how Kwux's visitors use its website. From time to time, Kwux may release non-personally-identifying information in
      the
      aggregate, e.g., by publishing a report on trends in the usage of its website.
    </p>

    <p class="mb-4 text-sm text-gray-700 leading-normal">
      Kwux also collects potentially personally-identifying information like Internet Protocol (IP) addresses. Kwux does
      not
      use such information to identify its visitors, however, and does not disclose such information, other than under
      the
      same circumstances that it uses and discloses personally-identifying information, as described below. We may also
      collect and use IP addresses to block users who violated our Terms of Service.
    </p>

    <h5>
      Gathering of Personally-Identifying Information
    </h5>

    <p class="mb-4 text-sm text-gray-700 leading-normal">
      Certain visitors to Kwux's websites choose to interact with Kwux in ways that require Kwux to gather
      personally-identifying information. The amount and type of information that Kwux gathers depends on the nature of
      the
      interaction. Kwux collects such information only insofar as is necessary or appropriate to fulfill the purpose of
      the
      visitor's interaction with Kwux. Kwux does not disclose personally-identifying information other than as described
      below. And visitors can always refuse to supply personally-identifying information, with the caveat that it may
      prevent them from engaging in certain Service-related activities.
    </p>

    <p class="mb-4 text-sm text-gray-700 leading-normal">
      Additionally, some interactions, such as posting a comment, may ask for optional personal information. For
      instance,
      when posting a comment, may provide a website that will be displayed along with a user's name when the comment is
      displayed. Supplying such personal information is completely optional and is only displayed for the benefit and
      the
      convenience of the user.
    </p>

    <h5>
      Aggregated Statistics
    </h5>

    <p class="mb-4 text-sm text-gray-700 leading-normal">
      Kwux may collect statistics about the behavior of visitors to the Service. For instance, Kwux may monitor the most
      popular parts of the kwux.com. Kwux may display this information publicly or provide it to others. However, Kwux
      does not
      disclose personally-identifying information other than as described below.
    </p>

    <h5>
      Protection of Certain Personally-Identifying Information
    </h5>

    <p class="mb-4 text-sm text-gray-700 leading-normal">
      Kwux discloses potentially personally-identifying and personally-identifying information only to those of its
      employees, contractors and affiliated organizations that (i) need to know that information in order to process it
      on
      Kwux's behalf or to provide services available at Kwux's websites, and (ii) that have agreed not to disclose it to
      others. Some of those employees, contractors and affiliated organizations may be located outside of your home
      country;
      by using the Service, you consent to the transfer of such information to them. Kwux will not rent or sell
      potentially
      personally-identifying and personally-identifying information to anyone. Other than to its employees, contractors
      and
      affiliated organizations, as described above, Kwux discloses potentially personally-identifying and
      personally-identifying information only when required to do so by law, or when Kwux believes in good faith that
      disclosure is reasonably necessary to protect the property or rights of Kwux, third parties or the public at
      large.
      If
      you are a registered user of the Service and have supplied your email address, Kwux may occasionally send you an
      email
      to tell you about new features, solicit your feedback, or just keep you up to date with what's going on with Kwux
      and
      our products. We primarily use our website and blog to communicate this type of information, so we expect to keep
      this
      type of email to a minimum. If you send us a request (for example via a support email or via one of our feedback
      mechanisms), we reserve the right to publish it in order to help us clarify or respond to your request or to help
      us
      support other users. Kwux takes all measures reasonably necessary to protect against the unauthorized access, use,
      alteration or destruction of potentially personally-identifying and personally-identifying information.
    </p>

    <h5>
      Cookies
    </h5>

    <p class="mb-4 text-sm text-gray-700 leading-normal">
      A cookie is a string of information that a website stores on a visitor's computer, and that the visitor's browser
      provides to the Service each time the visitor returns. Kwux uses cookies to help Kwux identify and track visitors,
      their usage of Kwux Service, and their Service access preferences. Kwux visitors who do not wish to have cookies
      placed on their computers should set their browsers to refuse cookies before using Kwux's websites, with the
      drawback
      that certain features of Kwux's websites may not function properly without the aid of cookies.
    </p>

    <h5>
      Data Storage
    </h5>

    <p class="mb-4 text-sm text-gray-700 leading-normal">
      Kwux uses third party vendors and hosting partners to provide the necessary hardware, software, networking,
      storage,
      and related technology required to run the Service. You understand that although you retain full rights to your
      data,
      it may be stored on third party storage and transmitted through third party networks.
    </p>

    <h5>
      Privacy Policy Changes
    </h5>

    <p class="mb-4 text-sm text-gray-700 leading-normal">
      Although most changes are likely to be minor, Kwux may change its Privacy Policy from time to time, and in Kwux's
      sole
      discretion. Kwux encourages visitors to frequently check this page for any changes to its Privacy Policy. Your
      continued use of this site after any change in this Privacy Policy will constitute your acceptance of such change.
    </p>
  </div>
</div>

app/views/shared/_analytics_resources.html.erb
<% if Rails.application.config.fathom[:site_id].present? %>
  <script src="https://cdn.usefathom.com/script.js" data-site="<%= Rails.application.config.fathom[:site_id] %>" defer></script>
<% end %>

app/views/waitlist/users/_form.html.erb
<div class="w-full flex flex-col rounded-lg m-2 p-3">
  <%= form_with(model: waitlist_user, class: "w-full") do |form| %>
    <% if waitlist_user.errors.any? %>
      <div id="error_explanation" class="flex flex-col bg-red-200 text-white font-medium rounded-lg mb-3 border-red-400 border-4 before:rounded-md before:absolute before:inset-0 before:border-2 before:border-black relative">
        <div class="text-center items-center border-b-2 px-3 py-2 border-b-black">
          <h2 class="font-bold text-gray-800"><%= t('.errors.header') %></h2>
        </div>

        <ul class="px-3 py-2 text-red-700">
          <% waitlist_user.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="flex flex-col space-y-1 md:space-y-2 items-center">
      <div class="border-2 border-black outline-2 outline-white w-full p-4 rounded-lg">
        <div class="w-full">
          <%= form.label :email_address, t('.email_address'), class: "block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
          <%= form.text_field :email_address,
                              placeholder: "fantastic-person+kwux@gmail.com",
                              class: "appearance-none block w-full bg-blue-500 text-white placeholder:text-white border-2 border-black rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white focus:text-black" %>
        </div>

        <div class="w-full">
          <%= form.label :business_type, t('.business_type'), class: "block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
          <%= form.select :business_type, Waitlist::User.business_types.keys,
                          { prompt: "Kwux is perfect for my\u2026" },
                          class: "block appearance-none w-full bg-blue-500 border-2 border-black text-white mb-3 py-3 px-4 pr-8 rounded leading-tight focus:outline-none focus:bg-white focus:border-gray-500 focus:text-black"
          %>
        </div>
      </div>

      <div class="flex justify-end w-full md:w-auto md:pt-2">
        <%= form.submit t('.submit'),
                        class: "w-full rounded-lg py-2 px-5 bg-green-500 text-black inline-block font-medium border-2 border-black cursor-pointer hover:shadow-solid-md hover:translate-x-[-0.25em] hover:translate-y-[-0.25em]" %>
      </div>
    </div>
  <% end %>
</div>

app/views/waitlist/users/_waitlist_user.html.erb
<div id="<%= dom_id waitlist_user %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Email address:</strong>
    <%= waitlist_user.email_address %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Business type:</strong>
    <%= waitlist_user.business_type %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Notes:</strong>
    <%= waitlist_user.notes %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this user", waitlist_user, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this user', edit_waitlist_user_path(waitlist_user), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/waitlist/users/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing user</h1>

  <%= render "form", waitlist_user: @waitlist_user %>

  <%= link_to "Show this user", @waitlist_user, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to users", waitlist_users_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/waitlist/users/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Users</h1>
    <%= link_to 'New user', new_waitlist_user_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="waitlist_users" class="min-w-full">
    <%= render @waitlist_users %>
  </div>
</div>

app/views/waitlist/users/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <%= turbo_frame_tag @waitlist_user do %>
    <%= render "form", waitlist_user: @waitlist_user %>
  <% end %>
</div>

app/views/waitlist/users/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @waitlist_user %>

    <%= link_to 'Edit this waitlist_user', edit_waitlist_user_path(@waitlist_user), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this waitlist_user', waitlist_user_path(@waitlist_user), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to waitlist_users', waitlist_users_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>